Description: Launchs EC2 instance and pulls and runs a container for the Terrain Generator app

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      SubnetId: subnet-075811427d5564cf9
      SecurityGroupIds:
        - sg-032bd1ff8cf77dbb9
      IamInstanceProfile: CAB432-Instance-Role
      ImageId: ami-03acdbc3824c0c85e
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -xe

          # Start Docker (should already be installed in AMI)
          systemctl start docker
          systemctl enable docker
          usermod -aG docker ubuntu

          # Pull private ECR image and start containers
          su - ubuntu -c "bash -c '
            aws ecr get-login-password --region ap-southeast-2 \
              | docker login --username AWS --password-stdin 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com

            cd /home/ubuntu/Terrain-Generator
            docker compose pull 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11547227-a1:latest
            docker compose up -d 
            '"