Description: Launches an EC2 instance via AutoScalingGroup and runs the Terrain Generator container

Parameters:
  QutUsername:
    Type: String
    Default: n11547227@qut.edu.au
  QutUsername2:
    Type: String
    Default: n11596708@qut.edu.au
  Purpose:
    Type: String
    Default: assessment 2


Resources:

  Group88LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: Group-88-Launch-Template
      LaunchTemplateData:
        InstanceType: t2.small
        ImageId: ami-0c1691a934175445e
        IamInstanceProfile:
          Name: CAB432-Instance-Role
        SecurityGroupIds:
          - sg-032bd1ff8cf77dbb9
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 15
              VolumeType: gp3
        TagSpecifications:
          - ResourceType: instance
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -xe

            systemctl start docker
            systemctl enable docker
            usermod -aG docker ubuntu

            BUCKET_NAME=$(aws ssm get-parameter \
              --name "/n11547227/terrain-app/s3-bucket" \
              --region ap-southeast-2 \
              --query "Parameter.Value" \
              --output text)

            DYNAMO_NAME=$(aws ssm get-parameter \
              --name "/n11547227/terrain-app/dynamo-name" \
              --region ap-southeast-2 \
              --query "Parameter.Value" \
              --output text)

            DB_HOST=$(aws ssm get-parameter \
              --name "/n11547227/terrain-app/db-host" \
              --region ap-southeast-2 \
              --with-decryption \
              --query "Parameter.Value" \
              --output text)

            DB_NAME=$(aws ssm get-parameter \
              --name "/n11547227/terrain-app/db-name" \
              --region ap-southeast-2 \
              --with-decryption \
              --query "Parameter.Value" \
              --output text)

            DB_USER=$(aws ssm get-parameter \
              --name "/n11547227/terrain-app/db-username" \
              --region ap-southeast-2 \
              --with-decryption \
              --query "Parameter.Value" \
              --output text)

            DB_PASSWORD=$(aws secretsmanager get-secret-value \
              --secret-id "n11547227/terrain-app/db-password" \
              --region ap-southeast-2 \
              --query "SecretString" \
              --output text | jq -r .password)

            MEMCACHED_URL=$(aws ssm get-parameter \
              --name "/n11547227/terrain-app/memcached-url" \
              --region ap-southeast-2 \
              --query "Parameter.Value" \
              --output text)

            COGNITO_SECRET=$(aws secretsmanager get-secret-value \
              --secret-id "n11547227/terrain-app/cognito-credentials" \
              --region ap-southeast-2 \
              --query "SecretString" \
              --output text)

            CLIENT_ID=$(echo $COGNITO_SECRET | jq -r .client_id)
            CLIENT_SECRET=$(echo $COGNITO_SECRET | jq -r .client_secret)
            USER_POOL_ID=$(echo $COGNITO_SECRET | jq -r .user_pool_id)


            mkdir -p /home/ubuntu/Terrain-Generator
            touch /home/ubuntu/Terrain-Generator/.env

            echo "S3_BUCKET=$BUCKET_NAME" >> /home/ubuntu/Terrain-Generator/.env
            echo "DYNAMO_NAME=$DYNAMO_NAME" >> /home/ubuntu/Terrain-Generator/.env
            echo "DB_HOST=$DB_HOST" >> /home/ubuntu/Terrain-Generator/.env
            echo "DB_NAME=$DB_NAME" >> /home/ubuntu/Terrain-Generator/.env
            echo "DB_USER=$DB_USER" >> /home/ubuntu/Terrain-Generator/.env
            echo "DB_PASSWORD=$DB_PASSWORD" >> /home/ubuntu/Terrain-Generator/.env
            echo "MEMCACHED_URL=$MEMCACHED_URL" >> /home/ubuntu/Terrain-Generator/.env
            echo "CLIENT_SECRET=$CLIENT_SECRET" >> /home/ubuntu/Terrain-Generator/.env
            echo "CLIENT_ID=$CLIENT_ID" >> /home/ubuntu/Terrain-Generator/.env
            echo "USER_POOL_ID=$USER_POOL_ID" >> /home/ubuntu/Terrain-Generator/.env

            su - ubuntu -c "bash -c '
              aws ecr get-login-password --region ap-southeast-2 \
                | docker login --username AWS --password-stdin 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com

              cd /home/ubuntu/Terrain-Generator
              docker compose pull 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11547227-a2:latest
              docker compose up -d
            '"

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - subnet-075811427d5564cf9
      MinSize: "1"
      MaxSize: "1"
      DesiredCapacity: "1"
      TargetGroupARNs:
        - arn:aws:elasticloadbalancing:ap-southeast-2:901444280953:targetgroup/Group-88-Winterscape-tg/cb52202b90e00630
      LaunchTemplate:
        LaunchTemplateId: !Ref Group88LaunchTemplate
        Version: !GetAtt Group88LaunchTemplate.LatestVersionNumber

     # Cognito User Pool (added as a new resource)
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: "Assessment 2 - Group 88 - WinterScape"
      MfaConfiguration: "ON"
      EnabledMfaTypes: 
        - EMAIL
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          TemporaryPasswordValidityDays: 7
      Schema:
        - Name: sub
          AttributeDataType: String
          Mutable: false
          Required: true
          StringAttributeConstraints:
            MinLength: 1
            MaxLength: 2048
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
          StringAttributeConstraints:
            MinLength: 0
            MaxLength: 2048
        - Name: email_verified
          AttributeDataType: Boolean
          Mutable: true
          Required: false
      AutoVerifiedAttributes:
        - email
      VerificationMessageTemplate:
        DefaultEmailOption: "CONFIRM_WITH_CODE"
      EmailConfiguration:
        EmailSendingAccount: "DEVELOPER"
        SourceArn: "arn:aws:ses:ap-southeast-2:901444280953:identity/cab432.com"
        From: "CAB432 logins <logins@cab432.com>"
      EmailVerificationMessage: "Your verification code is {####}."
      EmailVerificationSubject: CAB432 - Please verify your email
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate: []
      DeletionProtection: "ACTIVE"
      UsernameConfiguration:
        CaseSensitive: false
      UserPoolTags:
        qut-username: "n11596708@qut.edu.au"
        qut-username2: "n11547227@qut.edu.au"

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: "WinterScape - Group 88 - Assessment 2"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: true   # client secret
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - "https://d84l1y8p4kdic.cloudfront.net"
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - phone
      AllowedOAuthFlowsUserPoolClient: true
      PreventUserExistenceErrors: ENABLED
      EnableTokenRevocation: true
      EnablePropagateAdditionalUserContextData: false
      AuthSessionValidity: 3
    
  TerrainStylesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: n11547227-styles
      AttributeDefinitions:
        - AttributeName: qut-username
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: qut-username
          KeyType: HASH 
        - AttributeName: id
          KeyType: RANGE 
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: qut-username
          Value: n11547227@qut.edu.au
        - Key: qut-username2
          Value: n11596708@qut.edu.au
        - Key: purpose
          Value: assessment 2

  TerrainBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: n11547227-a2-terrains
      Tags:
        - Key: qut-username
          Value: n11547227@qut.edu.au
        - Key: qut-username2
          Value: n11596708@qut.edu.au
        - Key: purpose
          Value: assessment 2

  S3BucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/n11547227/terrain-app/s3-bucket"
      Type: String
      Value: "n11547227-a2-terrains"
      Tags:
        - Key: qut-username
          Value: !Ref QutUsername
        - Key: qut-username2
          Value: !Ref QutUsername2
        - Key: purpose
          Value: !Ref Purpose
  
  MemcachedCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: cache.t3.micro 
      Engine: memcached
      NumCacheNodes: 1
      ClusterName: group-88-winterscape-memcache 
      CacheSubnetGroupName: "CAB432-subnets"
      VpcSecurityGroupIds:
        - sg-07707a36aa1599475
    Tags:
      - Key: qut-username
        Value: !Ref QutUsername
      - Key: qut-username2
        Value: !Ref QutUsername2
      - Key: purpose
        Value: !Ref Purpose

  DynamoNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/n11547227/terrain-app/dynamo-name"
      Type: String
      Value: "n11547227-styles"
      Tags:
        - Key: qut-username
          Value: !Ref QutUsername
        - Key: qut-username2
          Value: !Ref QutUsername2
        - Key: purpose
          Value: !Ref Purpose

  DatabaseUserParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/n11547227/terrain-app/db-username"
      Type: String
      Value: "s289"
      Tags:
        - Key: qut-username
          Value: !Ref QutUsername
        - Key: qut-username2
          Value: !Ref QutUsername2
        - Key: purpose
          Value: !Ref Purpose

  DatabaseHostParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/n11547227/terrain-app/db-host"
      Type: String
      Value: "database-1-instance-1.ce2haupt2cta.ap-southeast-2.rds.amazonaws.com"
      Tags:
        - Key: qut-username
          Value: !Ref QutUsername
        - Key: qut-username2
          Value: !Ref QutUsername2
        - Key: purpose
          Value: !Ref Purpose
  
  DatabaseNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/n11547227/terrain-app/db-name"
      Type: String
      Value: "cohort_2025"
      Tags:
        - Key: qut-username
          Value: !Ref QutUsername
        - Key: qut-username2
          Value: !Ref QutUsername2
        - Key: purpose
          Value: !Ref Purpose

  MemcachedURLParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "/n11547227/terrain-app/memcached-url"
      Type: String
      Value: "group-88-winterscape-memcache.km2jzi.cfg.apse2.cache.amazonaws.com:11211"
      Tags:
        - Key: qut-username
          Value: !Ref QutUsername
        - Key: qut-username2
          Value: !Ref QutUsername2
        - Key: purpose
          Value: !Ref Purpose

  CognitoSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "n11547227/terrain-app/cognito-credentials"
      Description: "Cognito client credentials and user pool ID"
      SecretString: !Sub |
        {
          "client_id": "${CognitoUserPoolClient.ClientId}",
          "client_secret": "${CognitoUserPoolClient.ClientSecret}",
          "user_pool_id": "${CognitoUserPool}"
        }
      Tags:
        - Key: qut-username
          Value: !Ref QutUsername
        - Key: qut-username2
          Value: !Ref QutUsername2
        - Key: purpose
          Value: !Ref Purpose

Outputs:
  CognitoUserPoolId:
    Value: !Ref CognitoUserPool
    Export:
      Name: Group88-CognitoUserPoolId

  CognitoClientId:
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: Group88-CognitoClientId

  CognitoClientSecret:
    Value: !GetAtt CognitoUserPoolClient.ClientSecret
    Export:
      Name: Group88-CognitoClientSecret



      

