Description: Launchs EC2 instance and pulls and runs a container for the Terrain Generator app

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.small
      SubnetId: subnet-075811427d5564cf9
      SecurityGroupIds:
        - sg-032bd1ff8cf77dbb9
      IamInstanceProfile: CAB432-Instance-Role
      ImageId: ami-01dadc0959bc07dcb
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -xe

          # Start Docker (should already be installed in AMI)
          systemctl start docker
          systemctl enable docker
          usermod -aG docker ubuntu

          # Fetch bucket name from Parameter Store
          BUCKET_NAME=$(aws ssm get-parameter \
            --name "/n11547227/terrain-app/s3-bucket" \
            --region ap-southeast-2 \
            --query "Parameter.Value" \
            --output text)

          # Fetch DB credentials from Parameter Store
          DB_USER=$(aws ssm get-parameter \
            --name "/n11547227/terrain-app/db-username" \
            --region ap-southeast-2 \
            --with-decryption \
            --query "Parameter.Value" \
            --output text)

          DB_PASSWORD=$(aws secretsmanager get-secret-value \
            --secret-id "n11547227/terrain-app/db-password" \
            --region ap-southeast-2 \
            --query "SecretString" \
            --output text)

          # Write to .env file for Compose
          echo "S3_BUCKET=$BUCKET_NAME" >> /home/ubuntu/.env
          echo "DB_USER=$DB_USER" >> /home/ubuntu/.env
          echo "DB_PASSWORD=$DB_PASSWORD" >> /home/ubuntu/.env

          # Pull private ECR image and start containers
          su - ubuntu -c "bash -c '
            aws ecr get-login-password --region ap-southeast-2 \
              | docker login --username AWS --password-stdin 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com

            cd /home/ubuntu/Terrain-Generator
            docker compose pull 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11547227-a2:latest
            docker compose up -d 
            '"