Description: Launches an EC2 instance via AutoScalingGroup and runs the Terrain Generator container

Resources:

  Group88LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    DeletionPolicy: Retain
    Properties:
      LaunchTemplateName: Group-88-Launch-Template
      LaunchTemplateData:
        InstanceType: t2.small
        ImageId: ami-06bb01988f2118dc0
        IamInstanceProfile:
          Name: CAB432-Instance-Role
        SecurityGroupIds:
          - sg-032bd1ff8cf77dbb9
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 15
              VolumeType: gp3
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -xe

            systemctl start docker
            systemctl enable docker
            usermod -aG docker ubuntu

            BUCKET_NAME=$(aws ssm get-parameter \
              --name "/n11547227/terrain-app/s3-bucket" \
              --region ap-southeast-2 \
              --query "Parameter.Value" \
              --output text)

            DYNAMO_NAME=$(aws ssm get-parameter \
              --name "/n11547227/terrain-app/dynamo-name" \
              --region ap-southeast-2 \
              --query "Parameter.Value" \
              --output text)

            DB_USER=$(aws ssm get-parameter \
              --name "/n11547227/terrain-app/db-username" \
              --region ap-southeast-2 \
              --with-decryption \
              --query "Parameter.Value" \
              --output text)

            DB_PASSWORD=$(aws secretsmanager get-secret-value \
              --secret-id "n11547227/terrain-app/db-password" \
              --region ap-southeast-2 \
              --query "SecretString" \
              --output text | jq -r .password)

            REDIS_URL=$(aws ssm get-parameter \
              --name "/n11547227/terrain-app/redis-url" \
              --region ap-southeast-2 \
              --query "Parameter.Value" \
              --output text)

            COGNITO_SECRET=$(aws secretsmanager get-secret-value \
              --secret-id "n11547227/terrain-app/cognito" \
              --region ap-southeast-2 \
              --query "SecretString" \
              --output text)

            CLIENT_ID=$(echo $COGNITO_SECRET | jq -r .client_id)
            CLIENT_SECRET=$(echo $COGNITO_SECRET | jq -r .client_secret)
            USER_POOL_ID=$(echo $COGNITO_SECRET | jq -r .user_pool_id)


            mkdir -p /home/ubuntu/Terrain-Generator
            touch /home/ubuntu/Terrain-Generator/.env

            echo "S3_BUCKET=$BUCKET_NAME" >> /home/ubuntu/Terrain-Generator/.env
            echo "DYNAMO_NAME=$DYNAMO_NAME" >> /home/ubuntu/Terrain-Generator/.env
            echo "DB_USER=$DB_USER" >> /home/ubuntu/Terrain-Generator/.env
            echo "DB_PASSWORD=$DB_PASSWORD" >> /home/ubuntu/Terrain-Generator/.env
            echo "REDIS_URL=$REDIS_URL" >> /home/ubuntu/Terrain-Generator/.env
            echo "CLIENT_SECRET=$CLIENT_SECRET" >> /home/ubuntu/Terrain-Generator/.env
            echo "CLIENT_ID=$CLIENT_ID" >> /home/ubuntu/Terrain-Generator/.env
            echo "USER_POOL_ID=$USER_POOL_ID" >> /home/ubuntu/Terrain-Generator/.env

            su - ubuntu -c "bash -c '
              aws ecr get-login-password --region ap-southeast-2 \
                | docker login --username AWS --password-stdin 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com

              cd /home/ubuntu/Terrain-Generator
              docker compose pull 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11547227-a2:latest
              docker compose up -d
            '"

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - subnet-075811427d5564cf9
      MinSize: "1"
      MaxSize: "1"
      DesiredCapacity: "1"
      TargetGroupARNs:
        - arn:aws:elasticloadbalancing:ap-southeast-2:901444280953:targetgroup/Group-88-Winterscape-tg/cb52202b90e00630
      LaunchTemplate:
        LaunchTemplateId: !Ref Group88LaunchTemplate
        Version: !GetAtt Group88LaunchTemplate.LatestVersionNumber

  S3BucketParameter:
    Type: AWS::SSM::Parameter
    DeletionPolicy: Retain
    Properties:
      Name: "/n11547227/terrain-app/s3-bucket"
      Type: String
      Value: "n11547227-a2-terrains"

  DynamoNameParameter:
    Type: AWS::SSM::Parameter
    DeletionPolicy: Retain
    Properties:
      Name: "/n11547227/terrain-app/dynamo-name"
      Type: String
      Value: "n11547227-styles"

  DatabaseUserParameter:
    Type: AWS::SSM::Parameter
    DeletionPolicy: Retain
    Properties:
      Name: "/n11547227/terrain-app/db-username"
      Type: String
      Value: "s289"

  RedisURLParameter:
    Type: AWS::SSM::Parameter
    DeletionPolicy: Retain
    Properties:
      Name: "/n11547227/terrain-app/redis-url"
      Type: String
      Value: "rediss://master.group88-winterscape.km2jzi.apse2.cache.amazonaws.com:6379"

