services:
  backend:
    build: .
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11547227-a2:latest
    container_name: terrain-generator-backend
    ports:
      - "3000:3000" # host:container
    volumes:
      - .:/app      # bind mount for live code changes
      - /app/node_modules # prevent overwriting node_modules
      - ./videos:/videos
    environment:
      NODE_ENV: development
      DB_HOST: database-1-instance-1.ce2haupt2cta.ap-southeast-2.rds.amazonaws.com
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: cohort_2025
      S3_BUCKET: ${S3_BUCKET}
     

  redis:
    image: redis:alpine 
    container_name: redis
    volumes:
      - redis-data:/data 
    restart: always   

volumes:
  redis-data: