version: "3.8"

services:
  memcached:
    image: memcached
    container_name: memcached
    ports:
      - "11211:11211"

  terrain:
    build:
      context: ./src/terrains
      dockerfile: terrain.Dockerfile
    env_file:
      - .env
    ports:
      - "3002:3002"
    depends_on:
      - memcached
  
  snow:
    build:
      context: ./src/snow
      dockerfile: snow.Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - memcached

  authdata:
    build:
      context: ./src/authdata
      dockerfile: data.Dockerfile
    env_file:
      - .env
    ports:
      - "3003:3003"
    depends_on:
      - memcached
