version: "3.9"

services:
  backend:
    build: .
    container_name: terrain-generator
    ports:
      - "3000:3000" # host:container
    volumes:
      - .:/app      # bind mount for live code changes
      - /app/node_modules # prevent overwriting node_modules
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: terrainsdb
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: terrainsdb
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data: