version: "3.8"

services:
  memcached:
    image: memcached
    container_name: memcached
    ports:
      - "11211:11211"

  terrain:
    build:
      context: ./src/terrains
      dockerfile: terrain.Dockerfile
    env_file:
      - .env
    ports:
      - "3002:3002"
    depends_on:
      - memcached
  
  terrainstyles:
    build:
      context: ./src/terrainstyles
      dockerfile: terrainstyle.Dockerfile
    env_file:
      - .env
    ports:
      - "3004:3004"
    depends_on:
      - memcached
  
  snow:
    build:
      context: ./src/snow
      dockerfile: snow.Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - memcached

  authdata:
    build:
      context: ./src/authdata
      dockerfile: authdata.Dockerfile
    env_file:
      - .env
    ports:
      - "3003:3003"
    depends_on:
      - memcached
  
  # frontend:
  #   build:
  #     context: ./src/frontend
  #     dockerfile: frontend.Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - terrain
  #     - snow
  #     - authdata

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./src/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/frontend/UI:/usr/share/nginx/html/
      - ./src/frontend/styles:/usr/share/nginx/html/styles/
      - ./src/frontend/js:/usr/share/nginx/html/js/
    depends_on:
      - authdata
      - terrain
      - snow
